[package]
name = "mft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
chrono = "0.4"
uuid = {version = "1.1.2", features= ["v4"]}
base64 = "0.13.0"